<?xml version="1.0" encoding="utf-8"?><Database Name="Bills" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Bills;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="WindowsFormsApplinq.Properties.Settings" SettingsPropertyName="BillsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MonthlyBills" Member="MonthlyBills">
    <Type Name="MonthlyBill">
      <Column Name="BILL" AutoSync="OnUpdate" Type="System.String" DbType="VarChar(50)" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COST" AutoSync="OnUpdate" Type="System.Single" DbType="Real" CanBeNull="false" />
      <Column Name="Date" AutoSync="OnUpdate" Type="System.String" DbType="VarChar(2)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.KeyBalance" Member="KeyBalances">
    <Type Name="KeyBalance">
      <Column Name="KeyBalance" Member="KeyBalance1" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WeeklyBills" Member="WeeklyBills">
    <Type Name="WeeklyBill">
      <Column Name="Bill" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Single" DbType="Real" CanBeNull="true" />
    </Type>
  </Table>
</Database>